/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ["class"],
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
      extend: {
        colors: {
          border: "hsl(var(--border))",
          input: "hsl(var(--input))",
          ring: "hsl(var(--ring))",
          background: "hsl(var(--background))",
          foreground: "hsl(var(--foreground))",
          primary: {
            DEFAULT: "hsl(var(--primary))",
            foreground: "hsl(var(--primary-foreground))",
          },
          secondary: {
            DEFAULT: "hsl(var(--secondary))",
            foreground: "hsl(var(--secondary-foreground))",
          },
          destructive: {
            DEFAULT: "hsl(var(--destructive))",
            foreground: "hsl(var(--destructive-foreground))",
          },
          muted: {
            DEFAULT: "hsl(var(--muted))",
            foreground: "hsl(var(--muted-foreground))",
          },
          accent: {
            DEFAULT: "hsl(var(--accent))",
            foreground: "hsl(var(--accent-foreground))",
          },
          popover: {
            DEFAULT: "hsl(var(--popover))",
            foreground: "hsl(var(--popover-foreground))",
          },
          card: {
            DEFAULT: "hsl(var(--card))",
            foreground: "hsl(var(--card-foreground))",
          },
          // VSCode 原生颜色
          vscode: {
            // 背景色
            'editor-bg': 'var(--vscode-editor-background)',
            'editor-header-bg': 'var(--vscode-editorGroupHeader-tabsBackground)',
            'tab-inactive-bg': 'var(--vscode-tab-inactiveBackground)',
            'tab-active-bg': 'var(--vscode-tab-activeBackground)',
            'sidebar-bg': 'var(--vscode-sideBar-background)',
            'activitybar-bg': 'var(--vscode-activityBar-background)',
            'hover-bg': 'var(--vscode-toolbar-hoverBackground)',
            'input-bg': 'var(--vscode-input-background)',
            'button-bg': 'var(--vscode-button-background)',
            'button-hover-bg': 'var(--vscode-button-hoverBackground)',
            'button-secondary-bg': 'var(--vscode-button-secondaryBackground)',
            'button-secondary-hover-bg': 'var(--vscode-button-secondaryHoverBackground)',
            'dropdown-bg': 'var(--vscode-dropdown-background)',
            'list-hover-bg': 'var(--vscode-list-hoverBackground)',
            'list-selection-bg': 'var(--vscode-list-activeSelectionBackground)',
            'list-inactive-selection-bg': 'var(--vscode-list-inactiveSelectionBackground)',
            'badge-bg': 'var(--vscode-badge-background)',
            'error-bg': 'var(--vscode-errorBackground)',
            'warning-bg': 'var(--vscode-warningBackground)',
            // 文本颜色
            'editor-fg': 'var(--vscode-editor-foreground)',
            'sidebar-fg': 'var(--vscode-sideBar-foreground)',
            'sidebar-header-fg': 'var(--vscode-sideBarSectionHeader-foreground)',
            'activitybar-fg': 'var(--vscode-activityBar-foreground)',
            'activitybar-inactive-fg': 'var(--vscode-activityBar-inactiveForeground)',
            'input-fg': 'var(--vscode-input-foreground)',
            'input-placeholder-fg': 'var(--vscode-input-placeholderForeground)',
            'button-fg': 'var(--vscode-button-foreground)',
            'button-secondary-fg': 'var(--vscode-button-secondaryForeground)',
            'text-link-fg': 'var(--vscode-textLink-foreground)',
            'text-link-active-fg': 'var(--vscode-textLink-activeForeground)',
            'description-fg': 'var(--vscode-descriptionForeground)',
            'error-fg': 'var(--vscode-errorForeground)',
            'warning-fg': 'var(--vscode-warningForeground)',
            'dropdown-fg': 'var(--vscode-dropdown-foreground)',
            'badge-fg': 'var(--vscode-badge-foreground)',
            'list-selection-fg': 'var(--vscode-list-activeSelectionForeground)',
            // 边框颜色
            'sidebar-border': 'var(--vscode-sideBar-border)',
            'panel-border': 'var(--vscode-panel-border)',
            'group-border': 'var(--vscode-editorGroup-border)',
            'widget-border': 'var(--vscode-widget-border)',
            'input-border': 'var(--vscode-input-border)',
            'dropdown-border': 'var(--vscode-dropdown-border)',
            'focus-border': 'var(--vscode-focusBorder)',
            // 滚动条
            'scrollbar-slider-bg': 'var(--vscode-scrollbarSlider-background)',
            'scrollbar-slider-hover-bg': 'var(--vscode-scrollbarSlider-hoverBackground)',
            'scrollbar-slider-active-bg': 'var(--vscode-scrollbarSlider-activeBackground)',
            // 阴影
            'widget-shadow': 'var(--vscode-widget-shadow)',
          },
        },
        borderRadius: {
          lg: "var(--radius)",
          md: "calc(var(--radius) - 2px)",
          sm: "calc(var(--radius) - 4px)",
          'vs-sm': '2px',
          'vs-md': '4px',
          'vs-lg': '6px',
        },
        fontSize: {
          'vs-xs': '11px',
          'vs-sm': '12px',
          'vs-base': '13px',
          'vs-md': '14px',
          'vs-lg': '16px',
        },
        spacing: {
          'vs-xs': '4px',
          'vs-sm': '8px',
          'vs-md': '12px',
          'vs-lg': '16px',
          'vs-xl': '20px',
        },
      },
    },
    plugins: [],
  }